version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: passin-db
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - passin

  api-pass-in:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: passin-api
    ports:
      - 3333:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    networks:
      - passin
    depends_on:
      - postgres

  web-pass-in:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: passin-web
    ports:
      - 5173:${APP_PORT}
    environment:
      - VITE_API_URL=http://localhost:${API_PORT}
    networks:
      - passin
    depends_on:
      - api-pass-in

volumes:
  db:

networks:
  passin:
    driver: bridge
