POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 10
}
###
POST http://localhost:3333/events/a2f8809f-a6b7-4ec4-a5d0-7f0e4558a0fc/attendees
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@email.com"
}
###
GET http://localhost:3333/events/a2f8809f-a6b7-4ec4-a5d0-7f0e4558a0fc
###
GET http://localhost:3333/attendees/1/badge
###
GET http://localhost:3333/attendees/1/check-in
###
GET http://localhost:3333/events/a2f8809f-a6b7-4ec4-a5d0-7f0e4558a0fc/attendees?query=