version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: passin-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=passin=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - passin

  api-pass-in:
    build:
      context: .
    container_name: passin-api
    ports:
      - 3001:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - passin
    depends_on:
      - postgres

volumes:
  db:

networks:
  passin:
    driver: bridge
