name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/api/**
      - .github/workflows/**

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Build docker image
        run: docker build -t rafaelreisramos/nlw-unite:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        run: |
          docker push rafaelreisramos/nlw-unite:${{ steps.generate_sha.outputs.sha }}
          docker tag rafaelreisramos/nlw-unite:${{ steps.generate_sha.outputs.sha }} rafaelreisramos/nlw-unite:latest
          docker push rafaelreisramos/nlw-unite:latest
          
